[versions]
agp = "8.7.0"
kotlin = "2.0.0"

coreKtx = "1.13.1"
composeBom = "2024.09.02"
composeMaterial3 = "1.3.0"
composeActivity = "1.9.2"
composeShimmer = "1.3.1"
composeCoil = "2.7.0"
composeLottie = "6.5.2"

ktlint = "12.1.1"
detekt = "1.23.7"
detektCompose = "0.4.12"

desugaring = "2.1.2"

junit = "4.13.2"
junitVersion = "1.1.5"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

compose_bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose_animation = { module = "androidx.compose.animation:animation" }
compose_foundation = { module = "androidx.compose.foundation:foundation" }
compose_ui = { group = "androidx.compose.ui", name = "ui" }
compose_ui_util = { module = "androidx.compose.ui:ui-util" }
compose_ui_fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose_ripple = { module = "androidx.compose.material:material-ripple" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }

compose_activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose_shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
compose_coil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }
compose_lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "composeLottie" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

detekt_compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android_lint = { id = "com.android.lint", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
