name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check format with Ktlint
      run: ./gradlew ktlintCheck

    - name: Lint with Detekt
      run: ./gradlew detekt

    - name: Lint with Android
      run: ./gradlew lint

    - name: Build debug with Gradle
      run: ./gradlew assembleDebug
