name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Find keystore file
      run: echo "storeFile=$(pwd)/bb.jks" >> keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check format with Ktlint
      run: ./gradlew ktlintCheck

    - name: Lint with Detekt
      run: ./gradlew detekt

    - name: Lint with Android
      run: ./gradlew lint

    - name: Build release with Gradle
      run: ./gradlew assembleRelease

    - name: Find release file apk path
      id: releaseApk
      run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v4
      with:
        name: b.apk
        path: ${{ steps.releaseApk.outputs.apkfile }}
